package cn.hyperchain.browser.bean;


import lombok.Data;

import javax.validation.constraints.NotEmpty;


@Data
public class AccountEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.name
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    @NotEmpty(message = "用户名不能为空")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    @NotEmpty(message = "密码")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.mobile
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String mobile;


}