package cn.hyperchain.browser.bean;

public class AppEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.id
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.create_time
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.deleted
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.update_time
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.versions
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Integer versions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.api_code
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String apiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.api_desc
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String apiDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.api_name
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String apiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.api_url
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String apiUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.block_chain_code
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String blockChainCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.regulation
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String regulation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.requires
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String requires;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.status
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.id
     *
     * @return the value of api.id
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.id
     *
     * @param id the value for api.id
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.create_time
     *
     * @return the value of api.create_time
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.create_time
     *
     * @param createTime the value for api.create_time
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.deleted
     *
     * @return the value of api.deleted
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.deleted
     *
     * @param deleted the value for api.deleted
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.update_time
     *
     * @return the value of api.update_time
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.update_time
     *
     * @param updateTime the value for api.update_time
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.versions
     *
     * @return the value of api.versions
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Integer getVersions() {
        return versions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.versions
     *
     * @param versions the value for api.versions
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setVersions(Integer versions) {
        this.versions = versions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.api_code
     *
     * @return the value of api.api_code
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getApiCode() {
        return apiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.api_code
     *
     * @param apiCode the value for api.api_code
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setApiCode(String apiCode) {
        this.apiCode = apiCode == null ? null : apiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.api_desc
     *
     * @return the value of api.api_desc
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getApiDesc() {
        return apiDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.api_desc
     *
     * @param apiDesc the value for api.api_desc
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setApiDesc(String apiDesc) {
        this.apiDesc = apiDesc == null ? null : apiDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.api_name
     *
     * @return the value of api.api_name
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.api_name
     *
     * @param apiName the value for api.api_name
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setApiName(String apiName) {
        this.apiName = apiName == null ? null : apiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.api_url
     *
     * @return the value of api.api_url
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getApiUrl() {
        return apiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.api_url
     *
     * @param apiUrl the value for api.api_url
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setApiUrl(String apiUrl) {
        this.apiUrl = apiUrl == null ? null : apiUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.block_chain_code
     *
     * @return the value of api.block_chain_code
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getBlockChainCode() {
        return blockChainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.block_chain_code
     *
     * @param blockChainCode the value for api.block_chain_code
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setBlockChainCode(String blockChainCode) {
        this.blockChainCode = blockChainCode == null ? null : blockChainCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.regulation
     *
     * @return the value of api.regulation
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getRegulation() {
        return regulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.regulation
     *
     * @param regulation the value for api.regulation
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setRegulation(String regulation) {
        this.regulation = regulation == null ? null : regulation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.requires
     *
     * @return the value of api.requires
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getRequires() {
        return requires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.requires
     *
     * @param requires the value for api.requires
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setRequires(String requires) {
        this.requires = requires == null ? null : requires.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.status
     *
     * @return the value of api.status
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.status
     *
     * @param status the value for api.status
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}