package cn.hyperchain.browser.bean;

public class AppLogEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.id
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.create_time
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.deleted
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.update_time
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.versions
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Integer versions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.api_code
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String apiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.api_name
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String apiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.application_code
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String applicationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.application_name
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String applicationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.order_code
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.param_sm3
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String paramSm3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.request_time
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Long requestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.response_time
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private Long responseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.result_code
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String resultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.param
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log.result
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.id
     *
     * @return the value of app_log.id
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.id
     *
     * @param id the value for app_log.id
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.create_time
     *
     * @return the value of app_log.create_time
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.create_time
     *
     * @param createTime the value for app_log.create_time
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.deleted
     *
     * @return the value of app_log.deleted
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.deleted
     *
     * @param deleted the value for app_log.deleted
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.update_time
     *
     * @return the value of app_log.update_time
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.update_time
     *
     * @param updateTime the value for app_log.update_time
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.versions
     *
     * @return the value of app_log.versions
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Integer getVersions() {
        return versions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.versions
     *
     * @param versions the value for app_log.versions
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setVersions(Integer versions) {
        this.versions = versions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.api_code
     *
     * @return the value of app_log.api_code
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getApiCode() {
        return apiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.api_code
     *
     * @param apiCode the value for app_log.api_code
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setApiCode(String apiCode) {
        this.apiCode = apiCode == null ? null : apiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.api_name
     *
     * @return the value of app_log.api_name
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.api_name
     *
     * @param apiName the value for app_log.api_name
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setApiName(String apiName) {
        this.apiName = apiName == null ? null : apiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.application_code
     *
     * @return the value of app_log.application_code
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getApplicationCode() {
        return applicationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.application_code
     *
     * @param applicationCode the value for app_log.application_code
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setApplicationCode(String applicationCode) {
        this.applicationCode = applicationCode == null ? null : applicationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.application_name
     *
     * @return the value of app_log.application_name
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.application_name
     *
     * @param applicationName the value for app_log.application_name
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName == null ? null : applicationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.order_code
     *
     * @return the value of app_log.order_code
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.order_code
     *
     * @param orderCode the value for app_log.order_code
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.param_sm3
     *
     * @return the value of app_log.param_sm3
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getParamSm3() {
        return paramSm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.param_sm3
     *
     * @param paramSm3 the value for app_log.param_sm3
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setParamSm3(String paramSm3) {
        this.paramSm3 = paramSm3 == null ? null : paramSm3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.request_time
     *
     * @return the value of app_log.request_time
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Long getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.request_time
     *
     * @param requestTime the value for app_log.request_time
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setRequestTime(Long requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.response_time
     *
     * @return the value of app_log.response_time
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public Long getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.response_time
     *
     * @param responseTime the value for app_log.response_time
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setResponseTime(Long responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.result_code
     *
     * @return the value of app_log.result_code
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.result_code
     *
     * @param resultCode the value for app_log.result_code
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode == null ? null : resultCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.param
     *
     * @return the value of app_log.param
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.param
     *
     * @param param the value for app_log.param
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log.result
     *
     * @return the value of app_log.result
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log.result
     *
     * @param result the value for app_log.result
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }
}