package cn.hyperchain.browser.mapper;

import cn.hyperchain.browser.bean.AccountEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


@Mapper
public interface AccountEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    int insert(AccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    AccountEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    List<AccountEntity> selectAll();

    AccountEntity selectByNameAndPassword(String name, String password);

    AccountEntity selectByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    int updateByPrimaryKey(AccountEntity record);
}