package cn.hyperchain.browser.mapper;

import cn.hyperchain.browser.bean.AppEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AppEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    int insert(AppEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    AppEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    List<AppEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    int updateByPrimaryKey(AppEntity record);
}