package cn.hyperchain.browser.mapper;

import cn.hyperchain.browser.bean.AppLogEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AppLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_log
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_log
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    int insert(AppLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_log
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    AppLogEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_log
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    List<AppLogEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_log
     *
     * @mbg.generated Thu Jan 14 16:00:53 CST 2021
     */
    int updateByPrimaryKey(AppLogEntity record);
}